# Use official Python image
FROM python:3.11

# Set the working directory
WORKDIR /app

# Install Pipenv
RUN pip install pipenv

# Copy Pipfile and Pipfile.lock before installing dependencies
COPY Pipfile Pipfile.lock /app/

# Install dependencies using Pipenv
RUN pipenv install --dev --system --ignore-pipfile

# Expose FastAPI port
EXPOSE 8000
