version: "3.8"

services:
  fastapi-app:
    image: fastapi-local-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: fastapi-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
